# Generated by Django 3.1.6 on 2021-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20210328_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intltransferrequest',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='withdrawalhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
