# Generated by Django 3.1.6 on 2021-03-28 16:46

import banking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20210328_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('local', 'local'), ('intl', 'intl')], max_length=10)),
                ('transfer_id', models.UUIDField(unique=True)),
                ('code', models.UUIDField(default=banking.models.generate_code, unique=True)),
            ],
        ),
    ]
