# Generated by Django 3.1.6 on 2021-03-28 18:13

import banking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_authcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=models.CharField(default=banking.models.generate_code, max_length=48, unique=True),
        ),
    ]
