# Generated by Django 3.1.6 on 2021-04-26 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_auto_20210426_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intltransferrequest',
            name='date_initiated',
        ),
        migrations.RemoveField(
            model_name='localtransferrequest',
            name='date_initiated',
        ),
        migrations.AlterField(
            model_name='intltransferrequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='localtransferrequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
